env:
  es6: true
  jest: true
  node: true

extends:
  - eslint:recommended
  - plugin:react/recommended

parser: babel-eslint

rules:
  require-atomic-updates: off

settings:
  react:
    version: detect
