version: 2

jobs:
  app:
    working_directory: ~/httpdf

    docker:
      - image: circleci/node:10

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v2-{{ .Branch }}
            - v2-master-{{ checksum "yarn.lock" }}
            - v2-master

      - run:
          name: Install dependencies
          command: yarn

      - run:
          name: Check lockfile is up-to-date
          command: yarn check

      - run:
          name: Run server
          command: yarn dev
          background: true

      - run:
          name: Run tests
          command: yarn test

      - save_cache:
          key: v2-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.config/yarn
            - ~/.yarn
            - ~/httpdf/node_modules

  build:
    working_directory: ~/httpdf

    docker:
      - image: circleci/node:10

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build docker image
          command: make build

workflows:
  version: 2
  stack:
    jobs:
      - app
      - build
