on: push
name: CI
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: yarn install
      - name: Check lockfile is up to date
        run: yarn check

  build_and_test:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: yarn install
      - name: Build source
        run: yarn build:app
      - name: Prebuild documents
        run: yarn prebuild
        env:
          HTTPDF_DOCUMENTS_DIST: .build
          HTTPDF_DOCUMENTS_SRC: ./__tests__/documents
      - name: Run tests
        run: yarn test
        env:
          DEBUG: httpdf:*
          HTTPDF_DOCUMENTS_DIST: .build
          HTTPDF_DOCUMENTS_SRC: ./__tests__/documents
          PORT: "8000"

  build_image:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build image
        run: docker build -t n6g7/httpdf:latest .
